name: Build Native Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-native:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # --- Setup GraalVM instead of Temurin ---
      - name: Set up GraalVM for Java 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          components: 'native-image'
          cache: maven
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # --- Verify GraalVM is active ---
      - name: Check Java and native-image
        run: |
          java -version
          native-image --version

      # --- Build native executable ---
      - name: Build native image with Maven
        run: mvn -Pnative -DskipTests clean native:compile

      # --- Save the built native binary as an artifact ---
      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: native-binary
          path: target/*

      # --- Also upload build logs if you want to inspect them ---
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: target/native/compile.log
